import Head from 'next/head'

const Meta = () => {
    <Head>
        <title>CDS - Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
}

export default Meta